# ===== APP =====
spring.application.name=payday

# ===== DATABASE =====
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/payday}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Sa@100503}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== SERVER =====
server.port=8080

# ===== CORS =====
cors.allowed.origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}

# ===== LOGGING =====
logging.level.com.app.payday=DEBUG